### ISSUE TITLE
Images are broken (not showing) in android 9 (api level 28)."Glide: Load failed"

### ISSUE THREAD

**Issue by onqanetdev** [cometchat-pro-samples/android-java-chat-app#1]
2019-02-15 16:44:12.858 30077-30077/com.inscripts.cometchatpulse.demo W/Glide: Load failed for https://data.cometchat.com/assets/images/avatars/spiderman.png with size [100x100]
    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
    There was 1 cause:
    java.io.IOException(Cleartext HTTP traffic to data.cometchat.com.s3-eu-west-1.amazonaws.com not permitted)
     call GlideException#logRootCauses(String) for more detail
      Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE
    There was 1 cause:
    java.io.IOException(Cleartext HTTP traffic to data.cometchat.com.s3-eu-west-1.amazonaws.com not permitted)
     call GlideException#logRootCauses(String) for more detail
        Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetch failed
    There was 1 cause:
    java.io.IOException(Cleartext HTTP traffic to data.cometchat.com.s3-eu-west-1.amazonaws.com not permitted)
     call GlideException#logRootCauses(String) for more detail
          Cause (1 of 1): class java.io.IOException: Cleartext HTTP traffic to data.cometchat.com.s3-eu-west-1.amazonaws.com not permitted
2019-02-15 16:44:12.859 30077-30077/com.inscripts.cometchatpulse.demo I/Glide: Root cause (1 of 1)
    java.io.IOException: Cleartext HTTP traffic to data.cometchat.com.s3-eu-west-1.amazonaws.com not permitted
        at com.android.okhttp.HttpHandler$CleartextURLFilter.checkURLPermitted(HttpHandler.java:115)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:458)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
        at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:104)
        at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:122)
        at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:59)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:99)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.startNextOrFail(MultiModelLoader.java:150)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onLoadFailed(MultiModelLoader.java:144)
        at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:65)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:99)
        at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:62)
        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:302)
        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:272)
        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:233)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)
2019-02-15 16:44:13.717 30077-30077/com.inscripts.cometchatpulse.demo D/ViewRootImpl[OneToOneChatActivity]: changeCanvasOpacity: opaque=false

**Comment by yadavmangesh** [comment]
Hello @onqanetdev,

Thanks for pointing this out. We checked this at our end and were able to identify the cause of the issue. Starting with Android 9 (API level 28), cleartext support is disabled by default due to which Glide was unable to load the image. For more information you can refer to the below link from the official Android documentation:

https://developer.android.com/training/articles/security-config#CleartextTrafficPermitted

We have fixed this issue and updated the repo. You can pull the latest code changes and check again.

Thanks..!!
