### ISSUE TITLE
no such table: Presence (code 1 SQLITE_ERROR[1]): , while compiling: DROP TABLE Presence

### ISSUE THREAD

**Issue by aldrek** [cometchat-pro-samples/android-java-chat-app#17]
when I open the application it crashes 

error: 
sqlite.SQLiteException: no such table: Presence (code 1 SQLITE_ERROR[1]): , while compiling: DROP TABLE Presence
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1229)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:703)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:59)
        at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
        at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:2227)
        at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:2155)
        at com.cometchat.pro.repo.PresenceRepo.clearPresence(PresenceRepo.java:44)
        at com.cometchat.pro.core.SQLiteManager.deleteDatabase(SQLiteManager.java:65)
        at com.cometchat.pro.core.CometChat$44.onResponse(CometChat.java:1294)
        at com.cometchat.pro.core.ApiConnection.handleApiResponse(ApiConnection.java:981)
        at com.cometchat.pro.core.ApiConnection.access$000(ApiConnection.java:50)
        at com.cometchat.pro.core.ApiConnection$2.onResponse(ApiConnection.java:967)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)

**Comment by darshanbhanushali** [comment]
Hi @Ahmadgsalman which version of Cometchat SDK are you using.?
We have fixed the issue in version "2.0.0-beta4" . Kindly change your cometchat sdk version to beta4 and Let us know if you have the same issue.

**Comment by aldrek** [comment]
yes the issue has been fixed in beta 4
