### ISSUE TITLE
[2.0.2] Calling not working on obfuscation

### ISSUE THREAD

**Issue by jitvarpatil** [cometchat-pro-samples/android-java-chat-app#21]
**Describe the bug**
When the sample app has `minifyEnabled true` Call screen is crashing

**To Reproduce**
1. In build.gradle make `minifyEnabled true` and run the app
2. Call a user and when the call screen is launched it crashes

**Logs (Error Logs)**
- Error Log
`2020-01-28 17:13:54.044 31638-31638/com.inscripts.cometchatpulse.demo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.inscripts.cometchatpulse.demo, PID: 31638
    java.lang.IllegalStateException: java.lang.NoSuchFieldException: fill
        at com.horcrux.svg.v.a(RenderableView.java:544)
        at com.horcrux.svg.j.c(GroupView.java:98)
        at com.horcrux.svg.j.a(GroupView.java:81)
        at com.horcrux.svg.v.b(RenderableView.java:324)
        at com.horcrux.svg.B.a(SvgView.java:301)
        at com.horcrux.svg.B.j(SvgView.java:252)
        at com.horcrux.svg.B.onDraw(SvgView.java:104)
        at android.view.View.draw(View.java:20366)
        at android.view.View.updateDisplayListIfDirty(View.java:19241)
        at android.view.View.draw(View.java:20094)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
        at com.facebook.react.views.view.h.dispatchDraw(ReactViewGroup.java:713)
        at android.view.View.draw(View.java:20369)
        at android.view.View.updateDisplayListIfDirty(View.java:19241)
        at android.view.View.draw(View.java:20094)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
        at com.facebook.react.views.view.h.dispatchDraw(ReactViewGroup.java:713)
        at android.view.View.updateDisplayListIfDirty(View.java:19232)
        at android.view.View.draw(View.java:20094)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
        at com.facebook.react.views.view.h.dispatchDraw(ReactViewGroup.java:713)
        at android.view.View.draw(View.java:20369)
        at android.view.View.updateDisplayListIfDirty(View.java:19241)
        at android.view.View.draw(View.java:20094)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
        at com.facebook.react.views.view.h.dispatchDraw(ReactViewGroup.java:713)
        at android.view.View.updateDisplayListIfDirty(View.java:19232)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4321)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4294)
        at android.view.View.updateDisplayListIfDirty(View.java:19201)
        at android.view.View.draw(View.java:20094)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
        at d.d.m.M.dispatchDraw(ReactRootView.java:225)
        at android.view.View.draw(View.java:20369)
        at android.view.View.updateDisplayListIfDirty(View.java:19241)
        at android.view.View.draw(View.java:20094)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
        at android.view.View.draw(View.java:20369)
        at android.view.View.updateDisplayListIfDirty(View.java:19241)
        at android.view.View.draw(View.java:20094)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
        at android.view.View.updateDisplayListIfDirty(View.java:19232)
        at android.view.View.draw(View.java:20094)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
        at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:2023)
        at android.view.View.updateDisplayListIfDirty(View.java:19232)
        at android.view.View.draw(View.java:20094)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
        at android.view.View.updateDisplayListIfDirty(View.java:19232)
        at android.view.View.draw(View.java:20094)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
        at android.view.View.updateDisplayListIfDirty(View.java:19232)
        at android.view.View.draw(View.java:20094)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
        at android.view.View.updateDisplayListIfDirty(View.java:19232)
        at android.view.View.draw(View.java:20094)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)`

**Comment by jitvarpatil** [comment]
This issue is fixed with the latest release.
