### ISSUE TITLE
2.0.6[SDK-Version] CometChatMessageScreen.Activity : Facing null pointer Exception Issue

### ISSUE THREAD

**Issue by Julyars** [cometchat-pro-samples/android-java-chat-app#23]
**Describe the bug**
CometChatMessageScreen is not open in my project.it gives an error like below:

   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.app.skychat/screen.messagelist.CometChatMessageListActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.cometchat.pro.uikit.ComposeBox.ComposeBox.usedIn(java.lang.String)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2659)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6123)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.cometchat.pro.uikit.ComposeBox.ComposeBox.usedIn(java.lang.String)' on a null object reference
        at screen.messagelist.CometChatMessageScreen.initViewComponent(CometChatMessageScreen.java:312)

**Comment by darshanbhanushali** [comment]
Hi,

Based on the error log you shared, it seems like there is no reference of _composeBox_ in CometChatMessageScreen.java
Please add _composeBox_ reference or you can take a pull from this repository to get latest changes.
