### ISSUE TITLE
[3.0.1-1] Crash : Fatal Exception: java.lang.ClassCastException : CometChatMessageActions.java  

### ISSUE THREAD

**Issue by Nivs113** [cometchat-pro-samples/android-java-chat-app#26]
**App is crashing because of Fatal Exception: java.lang.ClassCastException : CometChatMessageActions.java  : line : 373**

![image](https://user-images.githubusercontent.com/26837785/149192385-0f5abae6-dddb-450a-9111-5d4947b80e90.png)

**Logs (Error Logs)**
`Fatal Exception: java.lang.ClassCastException: com.cometchat.pro.uikit.ui_components.messages.message_list.CometChatMessageListActivity cannot be cast to com.cometchat.pro.uikit.ui_components.messages.thread_message_list.CometChatThreadMessageListActivity
       at com.cometchat.pro.uikit.ui_components.messages.message_actions.CometChatMessageActions.onDismiss(CometChatMessageActions.java:373)
       at androidx.fragment.app.DialogFragment.dismissInternal(DialogFragment.java:253)
       at androidx.fragment.app.DialogFragment.dismiss(DialogFragment.java:222)
       at com.google.android.material.bottomsheet.BottomSheetDialogFragment.dismiss(BottomSheetDialogFragment.java:47)
       at com.cometchat.pro.uikit.ui_components.messages.message_actions.CometChatMessageActions$7.onClick(CometChatMessageActions.java:285)
       at android.view.View.performClick(View.java:8160)
       at android.widget.TextView.performClick(TextView.java:16222)
       at android.view.View.performClickInternal(View.java:8137)
       at android.view.View.access$3700(View.java:888)
       at android.view.View$PerformClick.run(View.java:30236)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8633)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
`
@darshanbhanushali

**Comment by ketanyekale** [comment]
This has been fixed. Please try v4.x
