### ISSUE TITLE
E/FirebaseInstanceId: Token retrieval failed: SERVICE_NOT_AVAILABLE

### ISSUE THREAD

**Issue by kittlsk** [cometchat-pro-samples/android-java-chat-app#4]
Thansk @yadavmangesh for your reply on my earlier issue. I followed the instructions and added google-services.json to my android project. I used "com.inscripts.cometchatpulse.demo" as the android package name as stated from the build.gradle. It managed to load the first screen via Android simulator and after I selected any of the superhero id, the following prompted.

2019-03-28 15:00:05.008 15339-15339/com.inscripts.cometchatpulse.demo W/MessengerIpcClient: Received response for unknown request: 1
2019-03-28 15:00:12.700 15339-15359/com.inscripts.cometchatpulse.demo E/FirebaseInstanceId: Token retrieval failed: SERVICE_NOT_AVAILABLE
2019-03-28 15:00:12.706 15339-15372/com.inscripts.cometchatpulse.demo W/MessengerIpcClient: Timing out request: 2
2019-03-28 15:00:14.562 15339-15339/com.inscripts.cometchatpulse.demo W/System.err: com.cometchat.pro.exceptions.CometChatException: Unable to resolve host "api.cometchat.com": No address associated with hostname
2019-03-28 15:00:14.562 15339-15339/com.inscripts.cometchatpulse.demo W/System.err: at com.cometchat.pro.core.ApiConnection$2.onFailure(ApiConnection.java:601)
2019-03-28 15:00:14.562 15339-15339/com.inscripts.cometchatpulse.demo W/System.err: at okhttp3.RealCall$AsyncCall.execute(RealCall.java:215)
2019-03-28 15:00:14.563 15339-15339/com.inscripts.cometchatpulse.demo W/System.err: at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
2019-03-28 15:00:14.563 15339-15339/com.inscripts.cometchatpulse.demo W/System.err: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2019-03-28 15:00:14.563 15339-15339/com.inscripts.cometchatpulse.demo W/System.err: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2019-03-28 15:00:14.563 15339-15339/com.inscripts.cometchatpulse.demo W/System.err: at java.lang.Thread.run(Thread.java:764)

**Comment by yadavmangesh** [comment]
Hello @kittlsk, 

Kindly let us know if your problem has been resolved or not.

Thanks
