### ISSUE TITLE
[Android 34] Voice call and video call button is crashing.

### ISSUE THREAD

**Issue by swatiomar27** [cometchat-pro-samples/android-java-chat-app#71]
**Describe the bug**
Voice call and video call button is crashing.

**To Reproduce**
1. Go to Calls
2. Click on Call button
3. Click on Voice call

**Expected behavior**
Call should be placed. App should not be crash.

**Enviorment/Platfrom (please complete the following information):**
 - Android API Version[ 34 ]
 - CometChat SDK Version[ 4.0.2]

**Logs (Error Logs)**
-   E  FATAL EXCEPTION: main
                                                                                                    Process: com.cometchat.kotlinsampleapp, PID: 15735
                                                                                                    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equalsIgnoreCase(java.lang.String)' on a null object reference
                                                                                                    	at com.cometchat.chatuikit.calls.callbutton.CallButtonsViewModel.initiateCall(CallButtonsViewModel.java:128)
                                                                                                    	at com.cometchat.chatuikit.calls.callbutton.CometChatCallButtons.lambda$init$0$com-cometchat-chatuikit-calls-callbutton-CometChatCallButtons(CometChatCallButtons.java:89)
                                                                                                    	at com.cometchat.chatuikit.calls.callbutton.CometChatCallButtons$$ExternalSyntheticLambda5.onClick(D8$$SyntheticClass:0)
                                                                                                    	at android.view.View.performClick(View.java:7659)
                                                                                                    	at android.view.View.performClickInternal(View.java:7636)
                                                                                                    	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
                                                                                                    	at android.view.View$PerformClick.run(View.java:30156)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8177)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

**Comment by swatiomar27** [comment]
How it resolved?

**Comment by Afroz-Cometchat** [comment]
Hi Swati,

We have created a ticket to address your concern.
Please find the ticket details [here](https://cometchat.zendesk.com/agent/tickets/30316)
In order to find more details we request you to please check your email inbox
